### ISSUE TITLE
正しく署名されていないリポジトリが追加されている

### ISSUE THREAD

**Issue by TMP-tenpura** [nexryai/naiad-linux#12]
問題のリポジトリのURLは http://download.opensuse.org/repositories/home:/antergos/xUbuntu_17.10 です。
恐らくlighten-webkit2-greeterのリポジトリかと思われますが、リポジトリ側で鍵の更新が一切行われていないので多分debファイル落としてインストールするスクリプト組むかバンドルした方がいいと思います。

**Comment by nexryai** [comment]
報告ありがとうございます。webkit2-greeterは将来的に廃止するためbeta5.2でそのレポジトリを削除します。

**Comment by nexryai** [comment]
beta6でこの問題を解決しました
