### ISSUE TITLE
live起動時にパスワードが要求される

### ISSUE THREAD

**Issue by nexryai** [nexryai/naiad-linux#4]
一時的な解決策としてパスワード"root7"と入力すれば先へ進めます。解決法は未定です。だれか教えてください。教えてくれたらなんでもします（嘘）

**Comment by yuuki76** [comment]
ん？今何でもするって言ったよね？
じゃあまずBuild方法を教えてくれるかな？

**Comment by nexryai** [comment]
PinguyOSのビルドツールPinguyBuilderを使用しています

**Comment by yuuki76** [comment]
これもうわかんねぇな

**Comment by nexryai** [comment]
草

**Comment by nexryai** [comment]
問題を解決したbeta5.1を公開しました。正確にはログイン画面の何もないところをクリックしないと先に進めませんがパスワードは要求されません

**Comment by nexryai** [comment]
以後この問題を
https://github.com/nexryai/naiad-linux/issues/9
に移動します
