### ISSUE TITLE
ログイン画面でエラー

### ISSUE THREAD

**Issue by toufune** [nexryai/naiad-linux#5]
![image](https://user-images.githubusercontent.com/61350984/83636616-35f9a800-a5e1-11ea-9f4c-26a1352f9a0e.png)

**Comment by toufune** [comment]
live起動です

**Comment by nexryai** [comment]
ご不便をお掛けして申し訳ありません。VirtualBoxの場合、isoをsataモードにすると直るようです。原因が判明し次第修正します

**Comment by toufune** [comment]
これsataなんですよね

**Comment by nexryai** [comment]
試しにキャンセルを押すとどうなりますか？

**Comment by toufune** [comment]
普通に使えますよ

**Comment by nexryai** [comment]
報告ありがとうございます。今後原因を調査していきます

**Comment by nexryai** [comment]
解決策を決定し、現在beta5.1に反映しています。具体的にはlihjtdm-webkit2-greeterをkylin-greeterに変更しました。

**Comment by nexryai** [comment]
beta5.1でこの問題を解決しました。
注意！ : virtualboxでは起動しません
